services:
    postgres:
        container_name: database
        ports:
            - "5432:5432"
        image: postgres
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./postgres_db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
            interval: 5s
            timeout: 60s
            retries: 5
            start_period: 80s
    server:
        container_name: server
        build:
            context: ./packages/backend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        command: bash -c "yarn start"
        environment:
            DATABASE_URL: "${DATABASE_URL}"
        depends_on:
            postgres:
                condition: service_healthy
    client:
        container_name: client
        build:
            context: ./packages/frontend
            dockerfile: Dockerfile
        command: bash -c "yarn dev"
        ports:
            - "5173:5173"
        depends_on:
            - server